//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/Services")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BookPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookNo {
            get {
                return this.BookNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNoField, value) != true)) {
                    this.BookNoField = value;
                    this.RaisePropertyChanged("BookNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BookPrice {
            get {
                return this.BookPriceField;
            }
            set {
                if ((this.BookPriceField.Equals(value) != true)) {
                    this.BookPriceField = value;
                    this.RaisePropertyChanged("BookPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        void AddBook(Client.WS.Book book);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookService/AddBook", ReplyAction="http://tempuri.org/IBookService/AddBookResponse")]
        System.IAsyncResult BeginAddBook(Client.WS.Book book, System.AsyncCallback callback, object asyncState);
        
        void EndAddBook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        Client.WS.Book[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        System.IAsyncResult BeginGetAllBooks(System.AsyncCallback callback, object asyncState);
        
        Client.WS.Book[] EndGetAllBooks(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/ReomveBook", ReplyAction="http://tempuri.org/IBookService/ReomveBookResponse")]
        void ReomveBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBookService/ReomveBook", ReplyAction="http://tempuri.org/IBookService/ReomveBookResponse")]
        System.IAsyncResult BeginReomveBook(string id, System.AsyncCallback callback, object asyncState);
        
        void EndReomveBook(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : Client.WS.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client.WS.Book[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client.WS.Book[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<Client.WS.IBookService>, Client.WS.IBookService {
        
        private BeginOperationDelegate onBeginAddBookDelegate;
        
        private EndOperationDelegate onEndAddBookDelegate;
        
        private System.Threading.SendOrPostCallback onAddBookCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllBooksDelegate;
        
        private EndOperationDelegate onEndGetAllBooksDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllBooksCompletedDelegate;
        
        private BeginOperationDelegate onBeginReomveBookDelegate;
        
        private EndOperationDelegate onEndReomveBookDelegate;
        
        private System.Threading.SendOrPostCallback onReomveBookCompletedDelegate;
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddBookCompleted;
        
        public event System.EventHandler<GetAllBooksCompletedEventArgs> GetAllBooksCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ReomveBookCompleted;
        
        public void AddBook(Client.WS.Book book) {
            base.Channel.AddBook(book);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddBook(Client.WS.Book book, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddBook(book, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndAddBook(System.IAsyncResult result) {
            base.Channel.EndAddBook(result);
        }
        
        private System.IAsyncResult OnBeginAddBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Client.WS.Book book = ((Client.WS.Book)(inValues[0]));
            return this.BeginAddBook(book, callback, asyncState);
        }
        
        private object[] OnEndAddBook(System.IAsyncResult result) {
            this.EndAddBook(result);
            return null;
        }
        
        private void OnAddBookCompleted(object state) {
            if ((this.AddBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddBookAsync(Client.WS.Book book) {
            this.AddBookAsync(book, null);
        }
        
        public void AddBookAsync(Client.WS.Book book, object userState) {
            if ((this.onBeginAddBookDelegate == null)) {
                this.onBeginAddBookDelegate = new BeginOperationDelegate(this.OnBeginAddBook);
            }
            if ((this.onEndAddBookDelegate == null)) {
                this.onEndAddBookDelegate = new EndOperationDelegate(this.OnEndAddBook);
            }
            if ((this.onAddBookCompletedDelegate == null)) {
                this.onAddBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddBookCompleted);
            }
            base.InvokeAsync(this.onBeginAddBookDelegate, new object[] {
                        book}, this.onEndAddBookDelegate, this.onAddBookCompletedDelegate, userState);
        }
        
        public Client.WS.Book[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllBooks(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllBooks(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client.WS.Book[] EndGetAllBooks(System.IAsyncResult result) {
            return base.Channel.EndGetAllBooks(result);
        }
        
        private System.IAsyncResult OnBeginGetAllBooks(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllBooks(callback, asyncState);
        }
        
        private object[] OnEndGetAllBooks(System.IAsyncResult result) {
            Client.WS.Book[] retVal = this.EndGetAllBooks(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllBooksCompleted(object state) {
            if ((this.GetAllBooksCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllBooksCompleted(this, new GetAllBooksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllBooksAsync() {
            this.GetAllBooksAsync(null);
        }
        
        public void GetAllBooksAsync(object userState) {
            if ((this.onBeginGetAllBooksDelegate == null)) {
                this.onBeginGetAllBooksDelegate = new BeginOperationDelegate(this.OnBeginGetAllBooks);
            }
            if ((this.onEndGetAllBooksDelegate == null)) {
                this.onEndGetAllBooksDelegate = new EndOperationDelegate(this.OnEndGetAllBooks);
            }
            if ((this.onGetAllBooksCompletedDelegate == null)) {
                this.onGetAllBooksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllBooksCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllBooksDelegate, null, this.onEndGetAllBooksDelegate, this.onGetAllBooksCompletedDelegate, userState);
        }
        
        public void ReomveBook(string id) {
            base.Channel.ReomveBook(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReomveBook(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReomveBook(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndReomveBook(System.IAsyncResult result) {
            base.Channel.EndReomveBook(result);
        }
        
        private System.IAsyncResult OnBeginReomveBook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return this.BeginReomveBook(id, callback, asyncState);
        }
        
        private object[] OnEndReomveBook(System.IAsyncResult result) {
            this.EndReomveBook(result);
            return null;
        }
        
        private void OnReomveBookCompleted(object state) {
            if ((this.ReomveBookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReomveBookCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReomveBookAsync(string id) {
            this.ReomveBookAsync(id, null);
        }
        
        public void ReomveBookAsync(string id, object userState) {
            if ((this.onBeginReomveBookDelegate == null)) {
                this.onBeginReomveBookDelegate = new BeginOperationDelegate(this.OnBeginReomveBook);
            }
            if ((this.onEndReomveBookDelegate == null)) {
                this.onEndReomveBookDelegate = new EndOperationDelegate(this.OnEndReomveBook);
            }
            if ((this.onReomveBookCompletedDelegate == null)) {
                this.onReomveBookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReomveBookCompleted);
            }
            base.InvokeAsync(this.onBeginReomveBookDelegate, new object[] {
                        id}, this.onEndReomveBookDelegate, this.onReomveBookCompletedDelegate, userState);
        }
    }
}
